[greeter]
theme-name = JamGrey
font-name = JetBrains Mono 10
cursor-theme-name = Bibata-Modern-Ice
indicators = 
background = /usr/share/backgrounds/login.png
default-user-image = /usr/share/backgrounds/avatar.png
icon-theme-name = Adwaita

